sudo: false

branches:
  only:
    - master

language: java
jdk:
  - oraclejdk8

script:
  - mvn clean package

after_success:
  - mvn jacoco:report coveralls:report clean

notifications:
  email:
    recipients:
      - sergey@shimkiv.com
    on_failure: always